on: [push]
name: Azure Bicep deploy testing new

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with: # Set Azure credentials secret as an input
       creds: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
       creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Deploy to Azure
    - uses: azure/arm-deploy@v1
      with: 
        subscriptionId: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: storageAccountType=Standard_LRS
        
 
