on: [push]
name: Azure Bicep deploy testing new
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: main.bicep storageAccountType=Standard_LRS 
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
 
