on: [push]
name: Azure Bicep deploy test

permissions:
  id-token: write
  contents: read
  
env:
    ENVIRONMENT: dev
    INPUT_REGION: westeurope
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with: # Set Azure credentials secret as an input
       creds: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      with: 
        resourceGroupName: ${{ secrets.AZURE_RG_NAME }}
        template: ./main.bicep
        parameters: ./parameters.dev.json
        scope: 'resourcegroup'
        region: ${{ env.INPUT_REGION }}
