on: [push]
name: Azure Bicep deploy testing new

env: 
    AZURE_RESOURCEGROUP_NAME: demo-app-service-rg
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: main.bicep storageAccountType=Standard_LRS 
 
