on: [push]
name: Azure Bicep deploy testing new

permissions:
  id-token: write
  contents: read
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with: # Set Azure credentials secret as an input
       credentials: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
       credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      with: 
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
        template: ./main.bicep
        parameters: environmentType=${{ env.ENVIRONMENT }}
        
 
