name: Caller workflow deploy Azure resources

# triggered when push is made to main 
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dev:
    name: Deploy to DEV
    # trigger for reusable workflow to start
    uses: ./.github/workflows/reusableDeployBicepFileWorkflow.yml 
    with:
      environmentType: dev
      resourceGroupName: fakeClientDevRG
    # inherits secrets from reusable workflow
    secrets: inherit 
      
  deploy_prod:
    name: Deploy to PROD
    # dependend on deploy_dev job to finish before starting
    needs: deploy_dev
    # trigger for reusable workflow to start
    uses: ./.github/workflows/reusableDeployBicepFileWorkflow.yml
    with:
      environmentType: prod
      resourceGroupName: fakeClientProdRG 
    # inherits secrets from reusable workflow
    secrets: inherit 
