name: Caller workflow publish Bicep 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish_appserviceplan:
    uses: ./.github/workflows/reusablePublishWorkflow.yml
    with:
      MODULE_NAME: appserviceplan
      MODULE_REGISTRY_SERVER: avanadeBicepContainerRegistry.azurecr.io
      MODULE_FILE_PATH: ./modules/appServicePlan.bicep 
      MODULE_METADATA_FILE_PATH: metadata.json
    secrets: inherit
      
  publish_sqldatabase:
    uses: ./.github/workflows/reusablePublishWorkflow.yml
    with:
      MODULE_NAME: sqldatabase
      MODULE_REGISTRY_SERVER: avanadeBicepContainerRegistry.azurecr.io
      MODULE_FILE_PATH: ./modules/sqlDatabase.bicep 
      MODULE_METADATA_FILE_PATH: metadata.json
    secrets: inherit

  publish_webapp:
    uses: ./.github/workflows/reusablePublishWorkflow.yml
    with:
      MODULE_NAME: webapp
      MODULE_REGISTRY_SERVER: avanadeBicepContainerRegistry.azurecr.io
      MODULE_FILE_PATH: ./modules/webApp.bicep 
      MODULE_METADATA_FILE_PATH: metadata.json
    secrets: inherit

