name: Deploy Template

on:
  workflow_call:
    inputs:
      environmentType:
        type: string
        required: true
      resourceGroupName:
        required: true
        type: string

jobs:
  validate:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: azure/login@v1
       with: 
        creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}
       env: 
        creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}

     - if: inputs.environmentType == 'prod'
       uses: azure/arm-deploy@v1
       name: Run what-if
       with:
         failOnStdErr: false
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./main.bicep
         parameters: environmentType=${{ inputs.environmentType }}
         additionalArguments: --what-if

  deploy:
    name: Start deployment to ${{ inputs.environmentType }}
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentType }}
    steps:
      # checkout code
    - uses: actions/checkout@main

      # log into azure
    - uses: azure/login@v1
      with: # set azure credentials secret as an input
       creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}
      env: # or as an environment variable
       creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}

    - uses: azure/arm-deploy@v1
      with: 
        resourcegroupname: ${{ inputs.resourceGroupName }}
        template: ./main.bicep
        parameters: ./parameters.dev.json
        scope: 'resourcegroup'
        region: westeurope
