name: Test Publish Bicep To ACR Workflow test

on: [push]
permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: appserviceplan
  MODULE_REGISTRY_SERVER: avanadeBicepContainerRegistry.azurecr.io
  MODULE_FILE_PATH: main.bicep
  MODULE_METADATA_FILE_PATH: metadata.json


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}
    - name: Run Bicep linter
      run: az bicep build --file ${{ env.MODULE_FILE_PATH }}
  
  publish:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS_CLIENT }}

    - name: TEST
      run: |
        for d in */
        do
            cd $d
            version="v$(cat metadata.json | jq -r '.version.major').$(cat metadata.json | jq -r '.version.minor')"
             if [ -z "$(az acr repository show -n ${{ env.MODULE_REGISTRY_SERVER }} --image ${{ env.MODULE_NAME }}/${d::-1}:$version 2>/dev/null)" ]; 
             then 
              echo "Publishing br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}//${d::-1}:$version";
              az bicep publish --file main.bicep --target "br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}/${d::-1}:$version";
             else 
              echo "Skipping br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}/${d::-1}:$version as it already exists";
             fi
             cd - > /dev/null
           done   

