name: Test Publish Bicep To ACR Workflow

on: [push]
permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: appServicePlan
  MODULE_REGISTRY_SERVER: shanbicepcontainerregistrytest.azurecr.io
  MODULE_FILE_PATH: main.bicep
  MODULE_METADATA_FILE_PATH: metadata.json


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
       creds: ${{ secrets.AZURE_CRED_TEST }}
    - name: Run Bicep linter
      run: az bicep build --file ${{ env.MODULE_FILE_PATH }}
  
  publish:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
       creds: ${{ secrets.AZURE_CRED_TEST }}
    - name: Get module version number
      run: |
        version="v$(cat metadata.json | jq -r '.version.major').$(cat metadata.json | jq -r '.version.minor')"
        if [ -z "$(az acr repository show -n ${{ secrets.ACR_SERVER }} --image bicep/modules/${d::-1}:$version 2>/dev/null)" ]; 
            then 
              echo "Publishing br:${{ secrets.ACR_SERVER }}/bicep/modules/${d::-1}:$version";
              az bicep publish --file main.bicep --target "br:${{ secrets.ACR_SERVER }}/bicep/modules/${d::-1}:$version";
            else 
              echo "Skipping br:${{ secrets.ACR_SERVER }}/bicep/modules/${d::-1}:$version as it already exists";
            fi
            cd - > /dev/null
          done
    - uses: azure/cli@v1
      name: Publish module
      with:
        inlineScript: |
          az bicep publish \
            --target 'br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}:${{ env.MODULE_VERSION }}' \
            --parameters version=${{ env.MODULE_VERSION }}\
            --file ${{ env.MODULE_FILE_PATH }}