name: test publish bicep to acr workflow

on: [push]
permissions:
  id-token: write
  contents: read

env:
  module_name: appserviceplan
  module_registry_server: avanadebicepcontainerregistry.azurecr.io
  module_file_path: ./main.bicep
  module_metadata_file_path: metadata.json


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: sign in to azure
      with:
       creds: ${{ secrets.azure_credentials_client }}
    - name: run bicep linter
      run: az bicep build --file ${{ env.module_file_path }}
    - name: print message        
      run: which bicep
      
  
  publish:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
 
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: sign in to azure
      with:
       creds: ${{ secrets.azure_credentials_client }}
    - name: get module version number
      run: |
        majorminorversionnumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' ${{ env.module_metadata_file_path }} -r )
        versionnumber="$majorminorversionnumber.${{ github.run_number }}"
        echo "module_version=$versionnumber" 
    - uses: actions/checkout@v2
    - uses: azure/cli@v1
      name: publish module
      with:
        azcliversion: latest
        inlinescript: |
          az /usr/local/bin/bicep publish \
            --target 'br:${{ env.module_registry_server }}/${{ env.module_name }}:${{ env.module_version }}' \
            --file ${{ env.module_file_path }}
            
            
            
