name: Sample workflow publiish sqldb

on:
    workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/workflowBreusable.yml
    with:
      MODULE_NAME: sqldatabase
      MODULE_REGISTRY_SERVER: avanadeBicepContainerRegistry.azurecr.io
      MODULE_FILE_PATH: ./modules/sqlDatabase.bicep 
      MODULE_METADATA_FILE_PATH: metadata.json

   

